version: '3.8'

services: 
  api: 
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment: 
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - RAZORPAY_API_KEY=${RAZORPAY_API_KEY}
      - RAZORPAY_API_SECRET=${RAZORPAY_API_SECRET}
      - RAZORPAY_SOURCE_ACCOUNT=${RAZORPAY_SOURCE_ACCOUNT}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  frontend: 
    build:
      context: ../admin-panel
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../admin-panel/.env
    volumes: 
      - ../admin-panel:/app
      - /app/node_modules
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV=development
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI}
      - AUTH0_POST_LOGOUT_REDIRECT_URI=${AUTH0_POST_LOGOUT_REDIRECT_URI}
    depends_on: 
      - api












# Use it incase you are using mongodb compass
  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   environment: 
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - mongodb_data:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network

# volumes:
#   mongodb_data:


networks:
  app-network:
    driver: bridge